### ISSUE TITLE
LibNaCLPK error

### ISSUE THREAD

**Issue by berendjan** [Tribler/kotlin-ipv8#31]
Hi,
I'm working on a trustchain implementation for a Covid app, I'm able to send / receive my own messages in string format. However sometimes the app crashes with the following stacktrace at seemingly random times.
I'm I working on an older version or am I doing something wrong in my message generator. 
[Full project on github](https://github.com/berendjan/Corona-Android-App)

Stacktrace
```
    java.lang.IllegalArgumentException: Bin prefix �-�����p��� does not match LibNaCLPK:
        at nl.tudelft.ipv8.keyvault.LibNaClPK$Companion.fromBin(LibNaClPK.kt:51)
        at nl.tudelft.ipv8.android.keyvault.AndroidCryptoProvider.keyFromPublicBin(AndroidCryptoProvider.kt:15)
        at nl.tudelft.ipv8.android.messaging.bluetooth.GattClientManager$IPv8GattCallback$initialize$2.onDataReceived(GattClientManager.kt:67)
        at no.nordicsemi.android.ble.ReadRequest.lambda$notifyValueChanged$0(ReadRequest.java:240)
        at no.nordicsemi.android.ble.-$$Lambda$ReadRequest$406mAhxV10eMfmbBI4l07-ac_9c.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Message
```
class MyMessage(val message: String) : Serializable {
    override fun serialize(): ByteArray {
        return message.toByteArray()
    }

    companion object Deserializer : Deserializable<MyMessage> {
        override fun deserialize(buffer: ByteArray, offset: Int): Pair<MyMessage, Int> {
            return Pair(MyMessage(buffer.toString(Charsets.UTF_8)), buffer.size)
        }
    }
}
```

send/reciever functions
```
    fun broadcastHelloMessage(peer : Peer, message: String) {
        val packet = serializePacket(MESSAGE_ID_HELLO, MyMessage(message))
        send(peer.address, packet)
    }
    /**
     * Receiving a packet from peer over network
     */
    private fun onHelloMessage(packet: Packet) {
        val (peer: Peer, payload: MyMessage) = packet.getAuthPayload(MyMessage.Deserializer)
        scope.launch{

            _message.value = "Recieved message '${payload.message}' from peer ${peer.mid}"
        }
    }
```

**Comment by MattSkala** [comment]
Hi, thanks for reporting the issue! From the provided stack trace, it looks like the public key stored in the identity characteristics of the other peer is not in a valid format. I'll add a try catch block so the application at least does not crash if that happens. However, I was not able to reproduce the crash and this error could be a consequence of other problems. Have you found any way to reproduce the crash, or does it happen completely at random?

**Comment by berendjan** [comment]
Hi, thanks for the reply!
It happens randomly, though I suspect it might be due to the DP3T library which also uses bluetooth for proximity tracing. I turned ble off for the trustchain and it works now without crashing. Thank you for looking into it!
